controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: "lateral_slider_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - lateral_slider_joint
  - name: "forward_slider_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - forward_slider_joint
